#!/bin/bash
# change this file to your needs

echo "Adding some modules"

# module add the_module_you_need_but_dont_deserve

echo "#################"
echo "    COMPILING    "
echo "#################"

gcc -Wall -g  -Ofast -Wextra ./src/main.c ./src/neural_network.c ./src/csv_to_array.c ./src/matrix.c ./src/activation.c -o main -lm -pthread

echo "#################"
echo "     RUNNING     "
echo "#################"

./main

cd python_evaluator
python3 evaluate.py ../actualTestPredictions ../data/fashion_mnist_test_labels.csv
