#!/bin/bash
# change this file to your needs

echo "Adding some modules"

# module add the_module_you_need_but_dont_deserve

echo "#################"
echo "    COMPILING    "
echo "#################"

gcc -Wall -g -O3 -Wextra ./src/main.c ./src/csv_to_array.c ./src/matrix.c ./src/activation.c -o main -lm

echo "#################"
echo "     RUNNING     "
echo "#################"

./main

