#!/bin/bash
# change this file to your needs

echo "Adding some modules"

# module add the_module_you_need_but_dont_deserve

echo "#################"
echo "    COMPILING    "
echo "#################"

gcc -Wall ./src/main.c ./src/activation.c -o main -lm

echo "#################"
echo "     RUNNING     "
echo "#################"

./main
